# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'poetTreeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for poetTreeApp
  # pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app/ios' 
  pod 'Firebase/Core', '~> 6.5.0'
  pod 'Firebase/Firestore', '~> 6.5.0'

end


