# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'poetTreeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for poetTreeApp

  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  pod 'RNFBFirestore', :path => '../node_modules/@react-native-firebase/firestore'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'

end


