# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'poetTreeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for poetTreeApp

  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Firestore', '~> 6.3.0'

end


